services:
  db:
    image: postgres:18.4
    container_name: db_karython
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

  backe_end:
    build: .
    restart: always
    container_name: karython_flask
    ports:
      - "5000:5000"
    env_file:
    - path: .env
      required: false
    depends_on:
    - db

volumes:
  psql_data:
